version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: caravan-coordinator_web_1
      APP_PORT: 8080

  web:
    image: caravanbitcoin/coordinator-umbrel:v1.0.0
    restart: on-failure
    stop_grace_period: 1m
    environment:
      BITCOIN_RPC_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_RPC_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_RPC_PASS: $APP_BITCOIN_RPC_PASS
